// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwcndbqedbowkgpbinxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Y25kYnFlZGJvd2tncGJpbnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDA5ODQsImV4cCI6MjA3MTk3Njk4NH0.mGjCCbnYh0QKT86rgknk5tgAZ-u2s-2Kt2sxrisabDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});